steps:
  - id: test-builds-successfully
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    dir: python-example-flask/
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud builds submit --config ./cloudbuild.yaml \
        --substitutions SHORT_SHA=${SHORT_SHA},_ARTIFACT_REGISTRY=${_ARTIFACT_REGISTRY},_ARTIFACT_REGISTRY_REPO=${_ARTIFACT_REGISTRY_REPO},_BUCKET_NAME=${_BUCKET_NAME}

  - id: cleanup
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gsutil rm gs://${_BUCKET_NAME}/${_VERSION}_test_log.xml
        gcloud artifacts docker images delete ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}
        gcloud run services delete helloworld-${_VERSION} --region us-central1 --quiet
